### ISSUE TITLE
Empty screen

### ISSUE THREAD

**Issue by eden-lane** [lahmatiy/react-render-tracker#15]
I'm getting following result after my app launch (but no errors):
![image](https://user-images.githubusercontent.com/2963477/133803737-ca6cdb1d-5324-4f9d-b2f1-460aaa6bca58.png)

My app is inside Docker container (nginx is also involved). Maybe I should open some port for react-render-tracker?

**Comment by lahmatiy** [comment]
Nope. There is an issue, when RRT sometimes doesn't load events from a page. See pending events in the toolbar. Just open and close devtools.
I will try to fix it, but it's hard to reproduce it.

**Comment by lahmatiy** [comment]
The issue was fixed in [version 0.4](https://github.com/lahmatiy/react-render-tracker/releases/tag/v0.4.0) that's just published. Thanks for reporting the issue.
