### ISSUE TITLE
Search by name doesn't work

### ISSUE THREAD

**Issue by MikeYermolayev** [lahmatiy/react-render-tracker#20]
Seems like search by display name doesn't work. The interesting part is that the component's name is underlined in the tree but I can't navigate to it.

I can see in the roadmap that `Filter events i.e. filter by component name, event type, duration etc` is not implemented yet but not sure if it's connected.

In the image below you can see that the name is underlined but there are no matches in the search bar.

P.S. I used inpage mode

![image](https://user-images.githubusercontent.com/8783498/142647952-2b133811-70d0-4757-9dec-8d41025f53c6.png)

**Comment by lahmatiy** [comment]
I can repro the issue. Don't know what the cause but it happens after events reset. Will fix soon

**Comment by lahmatiy** [comment]
Fix released in [v0.6.1](https://github.com/lahmatiy/react-render-tracker/releases/tag/v0.6.1)
