### ISSUE TITLE
Increase stack trace limit temporarily when tracing hooks back to their caller

### ISSUE THREAD

**Issue by chrishayesms** [lahmatiy/react-render-tracker#30]
Copying your own correspondence to me:

> The path is built using a hack based on a stack trace parsing. If it is truncated, then it will not be the full path (the initial parts will be missing, that is, only the tail will be displayed). The stack trace can be truncated by the runtime or a setting like Error.stackTraceLimit (⁠[details](https://v8.dev/docs/stack-trace-api)).

In my case, the trace only goes back 7 or 8 levels, which turns out to not quite get me to the original hook responsible for causing a re-render. It would be great if this can be made to get the full trace regardless of the browser settings.

**Comment by lahmatiy** [comment]
I've observed that the default value for `Error.stackTraceLimit` is 10 in V8, 50 in Firefox, and 100 in WebKit. Given that the stack trace capturing functionality adds approximately 4 entries to the stack trace, only around 6 entries remain for the hook path. I've refactored this stack trace capturing mechanism. Now, RRT temporarily sets `Error.stackTraceLimit` to 25 during stack trace capture, ensuring at least 20 path entries. Additionally, RRT employs a different method to extract paths, accommodating cases where a function is either unnamed or its name doesn't begin with use. I'm confident that RRT will now accurately process hook paths in the majority of scenarios.
