### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'hookIdx')

### ISSUE THREAD

**Issue by svagi** [lahmatiy/react-render-tracker#34]
Hi, I'm getting following error with the Rempl extension when using the latest version 0.7.1 of React Render Tracker. It works correctly when I use older version 0.7.0.

![image](https://github.com/lahmatiy/react-render-tracker/assets/1558135/e634462b-a29d-4535-bef8-7764b7b3c442)

**Comment by lahmatiy** [comment]
I found that bug is related to using `useSyncExternalStore()`. Working on fix...

**Comment by lahmatiy** [comment]
Just released [0.7.2](https://github.com/lahmatiy/react-render-tracker/releases/tag/v0.7.2) to address the issue.

**Comment by svagi** [comment]
Hi @lahmatiy, thanks for the fix! The error from the console is gone now, however nothing is rendering in the extension. This was also happening in v0.7.1. It works correctly in 0.7.0. 

<img width="646" alt="image" src="https://github.com/lahmatiy/react-render-tracker/assets/1558135/637515ee-8a21-462e-993c-619b4522a354">

**Comment by lahmatiy** [comment]
There is an error in UI. You don't see error messages since it embed into devtools. To see messages, use inpage sandbox for UI (see in readme), or open devtools as detached window and open a devtools for it using hot keys - you will see errors there.

**Comment by lahmatiy** [comment]
@svagi Looks like I found a root cause of the problem. There no errors in console, but a `<StrictMode>` fiber is missed in a log and components tree can be built. You can switch to parent-child hierarchy to see components (`<>` button). Working on a fix

**Comment by svagi** [comment]
@lahmatiy Great news! Switching works, thanks for the update! 👍

**Comment by lahmatiy** [comment]
Fixed in [0.7.3](https://github.com/lahmatiy/react-render-tracker/releases/tag/v0.7.3)

**Comment by svagi** [comment]
Great, thanks @lahmatiy! 🙌
