### ISSUE TITLE
react-render-tracker causes inifinite re-rendering w/  BrowserRouter from react-router-dom package and @tanstack/react-query

### ISSUE THREAD

**Issue by KalachevDev** [lahmatiy/react-render-tracker#35]
Since update 0.7.2 react-render-tracker started to cause infinite re-renders, see minimal repo with reproduction:

https://codesandbox.io/s/modest-saha-2iu6rd?file=/src/App.js

Once useQuery finished request BrowserRouter re-renders (not sure what causes the re-render itself) and useQuery sends request again. Without react-render-tracker it works just fine.

**Comment by lahmatiy** [comment]
Thank you for the report and repro code!
Working on a fix

**Comment by lahmatiy** [comment]
Fixed in [0.7.3](https://github.com/lahmatiy/react-render-tracker/releases/tag/v0.7.3)
