### ISSUE TITLE
Infinite event loading - `Loading events (0%)...`

### ISSUE THREAD

**Issue by svagi** [lahmatiy/react-render-tracker#37]
Howdy 👋 

I have a Next.js app where I'm trying to use react-render-tracker like this (same results with `inpage:true`)

![image](https://github.com/lahmatiy/react-render-tracker/assets/1558135/527d193b-101d-4067-af1e-ed7390e46587)

unfortunately the browser extension is stuck in infinite event loading despite the fact some pending events are already collected as shown on the screenshot bellow

![image](https://github.com/lahmatiy/react-render-tracker/assets/1558135/2ccea925-50cc-4b7f-9609-a9edd6926cfd)

Any idea what could be wrong? Thanks ahead.

**Comment by lahmatiy** [comment]
It's hard to say what's wrong at the moment. Any errors in a console?

**Comment by lahmatiy** [comment]
Did everything work well before 0.7.5?
Maybe you can provide a minimal case on which I can reproduce the problem?

**Comment by lahmatiy** [comment]
@svagi Thank you for the repro!
I found that the issue is related to hydration. Going to fix

**Comment by lahmatiy** [comment]
Fixed in [0.7.6](https://github.com/lahmatiy/react-render-tracker/releases/tag/v0.7.6)

**Comment by svagi** [comment]
@lahmatiy Works, thanks for the fix! 🙌
